
rem ********************************************************************
rem Create the COSTS table to hold the cost information for an item

Prompt ******  Creating COSTS table ....

CREATE TABLE costs
(
   prod_id      NUMBER         NOT NULL,
   time_id      DATE           NOT NULL,
   promo_id     NUMBER         NOT NULL,
   channel_id   NUMBER         NOT NULL,
   unit_cost    NUMBER(10,2)   NOT NULL,
   unit_price   NUMBER(10,2)   NOT NULL,
   CONSTRAINT costs_promo_fk
      FOREIGN KEY (promo_id)   REFERENCES promotions (promo_id),
   CONSTRAINT costs_product_fk
      FOREIGN KEY (prod_id)    REFERENCES products (prod_id),
   CONSTRAINT costs_time_fk
      FOREIGN KEY (time_id)    REFERENCES times (time_id),
   CONSTRAINT costs_channel_fk
      FOREIGN KEY (channel_id) REFERENCES channels (channel_id)
)
 --
 -- partitions
 --
 PARTITION BY RANGE (time_id)
  (
    PARTITION COSTS_Q1_2019 VALUES LESS THAN
       (TO_DATE('2019-04-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q2_2019 VALUES LESS THAN
       (TO_DATE('2019-07-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q3_2019 VALUES LESS THAN
       (TO_DATE('2019-10-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q4_2019 VALUES LESS THAN
       (TO_DATE('2020-01-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q1_2020 VALUES LESS THAN
       (TO_DATE('2020-04-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q2_2020 VALUES LESS THAN
       (TO_DATE('2020-07-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q3_2020 VALUES LESS THAN
       (TO_DATE('2020-10-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q4_2020 VALUES LESS THAN
       (TO_DATE('2021-01-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q1_2021 VALUES LESS THAN
       (TO_DATE('2021-04-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q2_2021 VALUES LESS THAN
       (TO_DATE('2021-07-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q3_2021 VALUES LESS THAN
       (TO_DATE('2021-10-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q4_2021 VALUES LESS THAN
       (TO_DATE('2022-01-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q1_2022 VALUES LESS THAN
       (TO_DATE('2022-04-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q2_2022 VALUES LESS THAN
       (TO_DATE('2022-07-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q3_2022 VALUES LESS THAN
       (TO_DATE('2022-10-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q4_2022 VALUES LESS THAN
       (TO_DATE('2023-01-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q1_2023 VALUES LESS THAN
       (TO_DATE('2023-04-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q2_2023 VALUES LESS THAN
       (TO_DATE('2023-07-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q3_2023 VALUES LESS THAN
       (TO_DATE('2023-10-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN')) COMPRESS,
    PARTITION COSTS_Q4_2023 VALUES LESS THAN
       (TO_DATE('2024-01-01','YYYY-MM-DD','NLS_CALENDAR=GREGORIAN'))
  )
;
